settings:
  # Available variables:
  # {mob_damage} - mob default damage
  # {mob_health} - mob default health
  # {level} - mob level
  # ANY PLAYER-UNRELATED PLACEHOLDERAPI PLACEHOLDER
  damage-formula: "{mob_damage}+({mob_damage}*{level}/100)" # A formula to calculate health of levelled mob
  health-formula: "{mob_health}*(1+{level}/100)" # A formula to calculate damage of levelled mob
  check-radius: 10 #A radius to check for players to calculate level
  display-by-range: true #Display custom mob names by range instead of only when hovering over them.
  display-range: 12 #Range to display custom mob names (Only if display-by-range is true)
  enable-mob-names: true #Wether plugin should add custom formatted names to mobs that it spawn
  name-format: "<dark_gray>[<color:#cfcb72>Lv.{lvl}</color>]</dark_gray> <dark_gray>[<red>{health}<gray>/</gray>{maxhealth}</red>]</dark_gray> <white>" #Custom mob name format
  health-format-max-places: 2
  mob-level-formula: "{sumlevel}/{playercount}"
  default-mob-level-formula: "{location_y}*0.01"

worlds:
  type: blacklist
  list: #The list itself (use - "*" to enable/disable all worlds). You can also use world_* to enable/disable all worlds that start with 'world_'
    - "Lobby"
    - "VoidWorld"

mob-replacements: # Supports any minecraft monster
  type: whitelist # whitelist/blacklist
  list: # he list itself (use - "*" to enable/disable all mobs)T
    - "*"
    - "ZOMBIE"

spawn-reasons: #https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  - "NATURAL"
  - "JOCKEY"
  - "SPAWNER"
  - "EGG"
  - "SPAWNER_EGG"
  - "LIGHTNING"
  - "BUILD_SNOWMAN"
  - "BUILD_IRONGOLEM"
  - "BUILD_WITHER"
  - "VILLAGE_DEFENSE"
  - "VILLAGE_INVASION"
  - "BREEDING"
  - "SLIME_SPLIT"
  - "REINFORCEMENTS"
  - "NETHER_PORTAL"
  - "DISPENSE_EGG"
  - "INFECTION"
  - "CURED"
  - "OCELOT_BABY"
  - "SILVERFISH_BLOCK"
  - "MOUNT"
  - "TRAP"
  - "ENDER_PEARL"
  - "SHOULDER_ENTITY"
  - "DROWNED"
  - "SHEARED"
  - "EXPLOSION"
  - "RAID"
  - "PATROL"
  - "BEEHIVE"
  - "PIGLIN_ZOMBIFIED"
  - "COMMAND"
  - "CUSTOM"
  - "DEFAULT"

messages: # Available message types: chat! actionbar! title!
  plugin-reloaded: "actionbar! &8(&6&l!&8) &7Plugin successfully reloaded!"
  no-permission: "chat! &8(&c&l&8) &7Insufficient permissions!"