settings:
  check-radius: 24
  display-by-range: true
  display-range: 12
  enable-mob-names: true
  health-format-max-places: 2

worlds:
  type: blacklist
  list:
    - "Lobby"
    - "VoidWorld"

mob-replacements:
  type: whitelist
  list:
    - "*"
    - "ZOMBIE"

spawn-reasons:
  - "NATURAL"
  - "JOCKEY"
  - "SPAWNER"
  - "EGG"
  - "SPAWNER_EGG"
  - "LIGHTNING"
  - "BUILD_SNOWMAN"
  - "BUILD_IRONGOLEM"
  - "BUILD_WITHER"
  - "VILLAGE_DEFENSE"
  - "VILLAGE_INVASION"
  - "BREEDING"
  - "SLIME_SPLIT"
  - "REINFORCEMENTS"
  - "NETHER_PORTAL"
  - "DISPENSE_EGG"
  - "INFECTION"
  - "CURED"
  - "OCELOT_BABY"
  - "SILVERFISH_BLOCK"
  - "MOUNT"
  - "TRAP"
  - "ENDER_PEARL"
  - "SHOULDER_ENTITY"
  - "DROWNED"
  - "SHEARED"
  - "EXPLOSION"
  - "RAID"
  - "PATROL"
  - "BEEHIVE"
  - "PIGLIN_ZOMBIFIED"
  - "COMMAND"
  - "CUSTOM"
  - "DEFAULT"

messages:
  plugin-reloaded: "actionbar! &8(&6&l!&8) &7Plugin successfully reloaded!"
  no-permission: "chat! &8(&c&l&8) &7Insufficient permissions!"